services:
  # --- DATABASE ---
  mysqldb:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
    ports:
      - "3307:3306"  # Laptop ka 3307 -> Docker ka 3306
    networks:
      - my-network

  # --- SPRING BOOT APP ---
  my-api:
    build: .
    ports:
      - "8080:8080"  # Laptop ka 8080 -> Docker ka 8080
    restart: on-failure  # Agar app crash ho, toh Docker use apne aap restart kare
    depends_on:
      - mysqldb
    environment:
      # Yahan dhyan de: Container ke andar hum mysqldb:3306 hi use karenge
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - my-network

networks:
  my-network:
    driver: bridge